### ISSUE TITLE
Simple instructions for getting started with Amber

### ISSUE THREAD

**Issue by danports** [danports/amber#13]
- [x] Upload bootstrap script to pastebin (pastebin script simply fetches the latest version of the amber nugget and runs it)
- [x] Get ambernuggets.cc URL up and running
- [x] Create an amber metapackage to enable a simpler install command (#44)
- [x] Decide on the right URL to use for the non-pastebin instructions
- [x] Check that `pastebin run` includes `shell` and the rest of the environment variables
- [x] The new installation (if you run `> amber install amber-client`) will not have the required prism libraries (see #29)
- [x] The new installation will try to access an Amber server by default and hang (see #33)
